### ISSUE TITLE
"install start" fails for me; delay between the two is required

### ISSUE THREAD

**Issue by BrannonKing** [Topshelf/Topshelf#243]
I've included my console output below. I would like to be able to install and start the service with one command. However, even calling with two separate commands in succession fails. If I don't wait several seconds after the install, the start call fails. What would be causing this?

```
D:\Workspace\Mobius7\Projects\MobiusServer.Bootstrapper\bin\Debug>..\..\..\MobiusServer\bin\Debug\MobiusServer.exe install start
Configuration Result:
[Success] Name MobiusServer
[Success] DisplayName Mobius Server
[Success] Description Mobius Server manages connections to autonomous vehicles and Mobius clients.
[Success] ServiceName MobiusServer
Topshelf v3.1.135.0, .NET Framework v4.0.30319.0

Running a transacted installation.

Beginning the Install phase of the installation.
Installing Mobius Server service
Installing service MobiusServer...
Service MobiusServer has been successfully installed.
Creating EventLog source MobiusServer in log Application...

The Install phase completed successfully, and the Commit phase is beginning.

The Commit phase completed successfully.

The transacted install has completed.
Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.InvalidOperationException: Cannot start service MobiusServer on computer '.'. ---> Syst
em.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()

D:\Workspace\Mobius7\Projects\MobiusServer.Bootstrapper\bin\Debug>..\..\..\MobiusServer\bin\Debug\MobiusServer.exe start
Configuration Result:
[Success] Name MobiusServer
[Success] DisplayName Mobius Server
[Success] Description Mobius Server manages connections to autonomous vehicles and Mobius clients.
[Success] ServiceName MobiusServer
Topshelf v3.1.135.0, .NET Framework v4.0.30319.0
The MobiusServer service was started.

D:\Workspace\Mobius7\Projects\MobiusServer.Bootstrapper\bin\Debug>..\..\..\MobiusServer\bin\Debug\MobiusServer.exe uninstall
Configuration Result:
[Success] Name MobiusServer
[Success] DisplayName Mobius Server
[Success] Description Mobius Server manages connections to autonomous vehicles and Mobius clients.
[Success] ServiceName MobiusServer
Topshelf v3.1.135.0, .NET Framework v4.0.30319.0


The uninstall is beginning.
Uninstalling MobiusServer service
Removing EventLog source MobiusServer.
Service MobiusServer is being removed from the system...
Service MobiusServer was successfully removed from the system.
Attempt to stop service MobiusServer.

The uninstall has completed.

D:\Workspace\Mobius7\Projects\MobiusServer.Bootstrapper\bin\Debug>..\..\..\MobiusServer\bin\Debug\MobiusServer.exe install && ..\..\..\MobiusServer\bin\Debug\Mo
biusServer.exe start
Configuration Result:
[Success] Name MobiusServer
[Success] DisplayName Mobius Server
[Success] Description Mobius Server manages connections to autonomous vehicles and Mobius clients.
[Success] ServiceName MobiusServer
Topshelf v3.1.135.0, .NET Framework v4.0.30319.0

Running a transacted installation.

Beginning the Install phase of the installation.
Installing Mobius Server service
Installing service MobiusServer...
Service MobiusServer has been successfully installed.
Creating EventLog source MobiusServer in log Application...

The Install phase completed successfully, and the Commit phase is beginning.

The Commit phase completed successfully.

The transacted install has completed.
Configuration Result:
[Success] Name MobiusServer
[Success] DisplayName Mobius Server
[Success] Description Mobius Server manages connections to autonomous vehicles and Mobius clients.
[Success] ServiceName MobiusServer
Topshelf v3.1.135.0, .NET Framework v4.0.30319.0
Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.InvalidOperationException: Cannot start service MobiusServer on computer '.'. ---> Syst
em.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()

```

**Comment by BrannonKing** [comment]
After posting this I realized there was a 3.2.0 update. It was either fixed in that update or related to a global mutex I was using.
