### ISSUE TITLE
Command-Line options are case sensitive

### ISSUE THREAD

**Issue by naveensrinivasan** [Topshelf/Topshelf#251]
The command line options for topshelf are case sensitive. Here in this example if I use ```Install``` instead of ```install``` it fails. Is this by design?   

```
WebAPIFileServer.exe Install
Topshelf.HostFactory Error: 0 : An exception occurred creating the host, Topshel
f.HostConfigurationException: The service was not properly configured:
[Failure] Command Line An unknown command-line option was found: ARGUMENT: Insta
ll
[Success] Name WebAPIFileServer
[Success] Description This is a FileServer.
[Success] ServiceName WebAPIFileServer
   at Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumera
ble`1 results)
   at Topshelf.HostFactory.New(Action`1 configureCallback)
Topshelf.HostFactory Error: 0 : The service terminated abnormally, Topshelf.Host
ConfigurationException: The service was not properly configured:
[Failure] Command Line An unknown command-line option was found: ARGUMENT: Insta
ll
[Success] Name WebAPIFileServer
[Success] Description This is a FileServer.
[Success] ServiceName WebAPIFileServer
   at Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumera
ble`1 results)
   at Topshelf.HostFactory.New(Action`1 configureCallback)
   at Topshelf.HostFactory.Run(Action`1 configureCallback)
```

**Comment by TravisTheTechie** [comment]
This seems like something we could support, case insensitive command line options.

**Comment by naveensrinivasan** [comment]
Could I take this one?

**Comment by TravisTheTechie** [comment]
Sure, you're welcomed to take a swing at it with a PR.
