### ISSUE TITLE
Service fails to respond to start command in a timely fashion

### ISSUE THREAD

**Issue by JGCreator** [Topshelf/Topshelf#495]
# I want to implement a strategy pattern ...
... for my service to run as a service _(both as a console service and an installed service)_ **OR** run as a one-time execution. The CMD argument driving the strategy decision is looked for before creating the Topshelf host. If any of the Topshelf commands are given, the decision is to use topshelf.

```
internal class Program
{
	public static void Main(string[] args)
	{
		string buildMode;
        if (args != null && args.Length > 0 && !TopShelfParameters.List.Contains(args[0]))
        {
            Log.Info($"First param not TopShelf cmd: {args[0]}");
            Log.Info("Setting arg[0] as buildMode.");
            buildMode = args[0];
        }
        else
        {
            Log.Info("Getting buildMode from AppSettings.");
            buildMode = ConfigurationManager.AppSettings["BuildMode"];
        }
		
		...
		
		var factory = new ExecutionStrategyFactory(appInfoBag, logFactory);
        var strategy = factory.GetStrategy();
		strategy.Execute();
	} // Main

} // Program

public static class TopShelfParameters
{
  public static System.Collections.Generic.List<string> List { get; } = new System.Collections.Generic.List<string>()
  {
    "run",
    "help",
    "install",
    "start",
    "stop",
    "uninstall"
  };
}

public class ExecutionStrategyFactory : OneTimeOrTopshelfStrategyFactory
{
    private readonly ILog _log;

    public ExecutionStrategyFactory(ApplicationInfoBag infoBag, ILogFactory logFactory)
        : base(infoBag)
    {
        _log = logFactory.GetLogger();

        try
        {
			...
		
            _oneTimeTimer = new OneTimeImmediatlyElapsingTimer();
            _standardTimer = new StandardTimerProxy(intervalMilliseconds);

            OneTimeService = () => new Service(..., _oneTimeTimer);
            RepeatingService = () => new Service(..., _standardTimer);
        }
        catch (Exception e)
        {
            _log.Error(e.Message, e);
            throw;
        }
    }

    private readonly ITimerProxy _oneTimeTimer;
    private readonly ITimerProxy _standardTimer;
}

public abstract class OneTimeOrTopshelfStrategyFactory : IExecutionStrategyFactory
{	
	protected Func<IService> OneTimeService { get; set; }
	
	protected Func<IService> RepeatingService { get; set; }
	
	protected OneTimeOrTopshelfStrategyFactory(ApplicationInfoBag infoBag)
	{
		...
	}
	
	public IExecutionStrategy GetStrategy()
	{
		if (this._infoBag.BuildMode == "Localhost")
			return (IExecutionStrategy) new SimpleStartInvocationStrategy(this.OneTimeService());
		return (IExecutionStrategy) new TopShelfExecutionStrategy(this.RepeatingService(), this._infoBag.ApplicationName, this._infoBag.Description, this._infoBag.RunAsUserName, this._infoBag.RunAsPassword);
	}
}

public class TopShelfExecutionStrategy : IExecutionStrategy
{
  private readonly IService _executionComponent;
  private readonly string _applicationName;
  private readonly string _description;
  private readonly string _runAsUserName;
  private readonly string _runAsPassword;

  public TopShelfExecutionStrategy(IService executionComponent, string applicationName, string description, string runAsUserName, string runAsPassword)
  {
    ...
  }

  public void Execute()
  {
    int num = (int) HostFactory.Run((Action<HostConfigurator>) (configurator =>
    {
      configurator.SetServiceName(this._applicationName);
      configurator.SetDisplayName(this._applicationName);
      configurator.SetDescription(this._description);
      configurator.StartAutomaticallyDelayed();
      configurator.RunAs(this._runAsUserName, this._runAsPassword);
      configurator.DependsOnEventLog();
      configurator.Service<IService>((Action<ServiceConfigurator<IService>>) (s =>
      {
        s.ConstructUsing<IService>((Func<IService>) (() => this._executionComponent));
        s.WhenStarted<IService>((Action<IService>) (service => service.Start()));
        s.WhenStopped<IService>((Action<IService>) (service => service.Stop()));
      }));
    }));
  }
}

/// A Pass-through proxy to System.Timers.Timer
public class StandardTimerProxy : ITimerProxy
{
  private readonly Timer _component;

  public StandardTimerProxy(double interval)
  {
    this._component = new Timer(interval);
  }

  bool ITimerProxy.AutoReset
  {
    get
    {
      return this._component.AutoReset;
    }
    set
    {
      this._component.AutoReset = value;
    }
  }

  bool ITimerProxy.Enabled
  {
    get
    {
      return this._component.Enabled;
    }
    set
    {
      this._component.Enabled = value;
    }
  }

  double ITimerProxy.Interval
  {
    get
    {
      return this._component.Interval;
    }
    set
    {
      this._component.Interval = value;
    }
  }

  event ElapsedEventHandler ITimerProxy.Elapsed
  {
    add
    {
      this._component.Elapsed += value;
    }
    remove
    {
      this._component.Elapsed -= value;
    }
  }

  void ITimerProxy.Dispose()
  {
    this._component.Dispose();
  }

  void ITimerProxy.Start()
  {
    this._component.Start();
  }

  void ITimerProxy.Stop()
  {
    this._component.Stop();
  }
}

public class Service : IDisposable, IService
{
    public Service(IWorkItemProcessor workItemProcessor, IMicromanager micromanager, ITimerProxy timer, ILogFactory logFactory)
    {
        ...
        _timer.Elapsed += OnElapsedTime;
    }

    public void Dispose()
    {
        ...
    }

    public void Start()
    {
        _log.Info($"Start called.");
        _log.Info($"Starting timer: {_timer}");
        _timer.Start();
    }

    public void Stop()
    {
        _log.Info($"Stop called.");
        _log.Info($"Stopping timer: {_timer}");
        _timer.Stop();
    }

    protected virtual void Dispose(bool disposing)
    {
        ...
    }

    private void OnElapsedTime(object sender, ElapsedEventArgs e)
    {
        _log.Info($"Timer elapsed! Calling MicromanageQuietly.");
        _micromanager.MicromanageQuietly(() =>
                                             {
                                                 var mLog = _logFactory.GetLogger();
                                                 try
                                                 {
                                                     mLog.Info($"Stopping timer before Process().");
                                                     _timer.Stop();
													 
                                                     mLog.Info("Processing...");
                                                     _workItemProcessor.Process();
                                                     mLog.Info("Processed!");
                                                 }
                                                 finally
                                                 {
                                                     mLog.Info("finally: Starting timer.");
                                                     _timer.Start();
                                                     mLog.Info("finally: Timer started.");
                                                 }
                                             });
    }

    private bool _disposed;
    private readonly IMicromanager _micromanager;
    private readonly ITimerProxy _timer;
    private readonly IWorkItemProcessor _workItemProcessor;
    private readonly ILogFactory _logFactory;
    private readonly ILog _log;
}
```

# The **Log** file I'm writing looks like this:

```
14:52:15,447 [1] INFO Program.cs - ================================================================
14:52:15,603 [1] INFO Program.cs - Program start - Arguments: ["install","start"]
14:52:15,603 [1] INFO Program.cs - Getting buildMode from AppSettings.
14:52:15,603 [1] INFO Program.cs - Validating buildMode value read: Development
14:52:15,603 [1] INFO Program.cs - Set db context initializer to null.
14:52:15,790 [1] INFO Program.cs - ApplicationInfoBag created: [Redacted]
14:52:15,790 [1] INFO Program.cs - Creating ExecutionStrategyFactory.
14:52:15,806 [1] INFO ExecutionStrategyFactory.cs - Getting interval.
14:52:15,806 [1] INFO ExecutionStrategyFactory.cs - Interval: 300000
14:52:15,806 [1] INFO ExecutionStrategyFactory.cs - Getting connection string from provider. ApplicationName: VerificationService BuildMode: Development
14:52:15,806 [1] INFO ExecutionStrategyFactory.cs - Connection string provided: [Redacted]
14:52:15,806 [1] INFO ExecutionStrategyFactory.cs - Wrappers creates.
14:52:15,821 [1] INFO ExecutionStrategyFactory.cs - Changeset info provided: [Redacted]
14:52:15,821 [1] INFO ExecutionStrategyFactory.cs - Repository created with ctx factory injected.
14:52:15,821 [1] INFO ExecutionStrategyFactory.cs - WorkItemProcessor created.
14:52:15,821 [1] INFO ExecutionStrategyFactory.cs - Micromanager created.
14:52:15,821 [1] INFO ExecutionStrategyFactory.cs - Timers created.
14:52:15,821 [1] INFO ExecutionStrategyFactory.cs - Service ctor delegates populated.
14:52:15,821 [1] INFO Program.cs - Getting execution strategy.
14:52:15,821 [1] INFO Program.cs - Executing strategy.
14:52:38,706 [1] INFO Program.cs - Strategy executed.
```

I've done some redacting here, but **Notice** that there is no entry in the log specifying that _"Start Called"_

# The console output of running the ".exe install start" command 
```
Configuration Result:
[Success] Name VerificationService
[Success] Description Verifies ...
[Success] ServiceName VerificationService
Topshelf v3.3.154.0, .NET Framework v4.0.30319.42000

Running a transacted installation.

Beginning the Install phase of the installation.
Installing VerificationService service
Installing service VerificationService...
Service VerificationService has been successfully installed.

The Install phase completed successfully, and the Commit phase is beginning.

The Commit phase completed successfully.

The transacted install has completed.
Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.InvalidOperationException: Cannot start service VerificationService on computer '.'. ---> System.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()

```

Is there something about my accessing the argument array that is messing with the `Topshelf.CommandLineParser.CommandLine` class retrieving arguments? It doesn't seem so because the install works correctly.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
