### ISSUE TITLE
TopShelf Runtime error in Mac .NET Framework v4.0.30319.42000

### ISSUE THREAD

**Issue by ugenlik** [Topshelf/Topshelf#505]
I have dotnet 2.1 installed and Mono with .NETFramework v4.5.2 Installed on my Mac. 

My project builds without any issues, but when I run the service I get 

```
/usr/local/share/dotnet/dotnet /Users/username/Git/FirestoreSync/MHD.Services.FirestoreSync/bin/Debug/netcoreapp2.1/MHD.Services.FirestoreSync.dll
Configuration Result:
[Success] Name FirestoreSync
[Success] Description Sync generated Elasticsearch documents into Firestore
[Success] ServiceName FirestoreSync
Topshelf v4.2.0.196, .NET Framework v4.0.30319.42000
Topshelf.Runtime.Windows.WindowsHostEnvironment Error: 0 : Unable to get parent process (ignored), System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libkernel32.dll, 1): image not found
   at Topshelf.Runtime.Windows.Kernel32.CreateToolhelp32Snapshot(UInt32 dwFlags, UInt32 th32ProcessID)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.GetParent(Process child)
Topshelf.HostFactory Error: 0 : The service terminated abnormally, System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
   at System.ServiceProcess.ServiceController.GetServices()
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.IsServiceListed(String serviceName)
   at Topshelf.Hosts.ConsoleRunHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

Process finished with exit code 0.
```

Does that mean Topshelf is trying to get  `.NET Framework v4.0.` ?? 

I dont get where `.NET Framework v4.0.30319.42000` coming from. 

Here is how I start the service
```
 HostFactory.Run(x =>
            {
                x.Service<IService>(s =>
                {
                    s.ConstructUsing(_ => service);
                    s.WhenStarted(ws => ws.Start());
                    s.WhenStopped(ws => ws.Stop());
                    
                });

                x.OnException(ex => _logger.Error(ex));

                x.SetDescription("Sync generated Elasticsearch documents into Firestore");
                x.SetDisplayName("FirestoreSync");
                x.SetServiceName("FirestoreSync");
            });
```

**Comment by phatboyg** [comment]
Is your csproj targeting netcoreapp2.0 or later? Seems like you're trying to run .NET framework Windows service on a Mac.

**Comment by ugenlik** [comment]
Yes this is happening on mac, csproj is targetting dotnet core 2.0 . Yeah I guess I have to use a windows machine. I was wondering where is `Topshelf v4.2.0.196, .NET Framework v4.0.30319.42000` line coming from.

**Comment by phatboyg** [comment]
The WindowsHostEnvironment seems suspect to me, honestly. I didn't think that was in the .NET core build.
