### ISSUE TITLE
System.OverflowException: Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by replaysMike** [Topshelf/Topshelf#561]
I'm not sure why this is happening and I've been debugging it for hours. When stopping the service on some environments the service is crashing and a dump file is created. Upon inspection, I'm seeing this:

```
The process was terminated due to an unhandled exception. Exception Info: System.OverflowException: Arithmetic operation resulted in an overflow. 

   at System.IO.StreamWriter.Write(String value) in /_/src/System.Private.CoreLib/shared/System/IO/StreamWriter.cs:line 459
   at System.IO.TextWriter.SyncTextWriter.Write(String value) in /_/src/System.Private.CoreLib/shared/System/IO/TextWriter.cs:line 831
   at System.Console.Write(String value) in /_/src/System.Console/src/System/Console.cs:line 684
   at Topshelf.Logging.TopshelfConsoleTraceListener.Write(String message)
   at System.Diagnostics.TraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id) in /_/src/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceListener.cs:line 412
   at System.Diagnostics.TraceListener.TraceData(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, Object[] data) in /_/src/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceListener.cs:line 361
   at System.Diagnostics.TraceSource.TraceData(TraceEventType eventType, Int32 id, Object[] data) in /_/src/System.Diagnostics.TraceSource/src/System/Diagnostics/TraceSource.cs:line 373
   at Topshelf.Logging.TraceLogWriter.LogInternal(LoggingLevel level, Object obj, Exception exception)
   at Topshelf.Logging.TraceLogWriter.Fatal(Object message, Exception exception)
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStop()
   at System.ServiceProcess.ServiceBase.DeferredStop() in E:\A\_work\39\s\corefx\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceBase.cs:line 530
   at System.ServiceProcess.ServiceBase.<>c__DisplayClass70_0.<ServiceCommandCallback>b__2(Object _) in E:\A\_work\39\s\corefx\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceBase.cs:line 808
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi) in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 808
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 335
   at System.Threading.QueueUserWorkItemCallback.Execute() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 824
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 677
```
The underlying stream is likely being allocated too large for some reason, and I can't identify the cause. We are using NLog and this is .Net Core 3.1

Setup code:

```
var logger = provider.GetService<ILogger>();
var type = typeof(T);
var displayName = type.GetDisplayName();
var serviceName = displayName.Replace(" ", "");
var serviceDescription = typeof(T).GetDescription();
var timeout = TimeSpan.FromSeconds(TimeoutSeconds);
return HostFactory.New(x => {
    x.Service<T>((sc) => {
        container.RegisterConstructorDependency<HostSettings>((factory, info) => sc);
        return provider.GetRequiredService<T>();
    });
    x.SetServiceName(serviceName);
    x.SetDescription(serviceDescription);
    x.SetDisplayName(displayName);
    x.BeforeInstall(() => {
        logger.LogInformation($"Installing service {serviceName}...");
    });
    x.BeforeUninstall(() => {
        logger.LogInformation($"Uninstalling service {serviceName}...");
    });
    x.AfterInstall(() => {
        logger.LogInformation($"{serviceName} service installed.");
    });
    x.AfterUninstall(() => {
        logger.LogInformation($"{serviceName} service uninstalled.");
    });
    x.OnException((ex) => {
        logger.LogError(ex, $"{serviceName} exception thrown: {ex.GetBaseException().Message}");
    });
    x.UnhandledExceptionPolicy = Topshelf.Runtime.UnhandledExceptionPolicyCode.LogErrorAndStopService;
});
```

**Comment by lauxjpn** [comment]
Seems like the stack trace is not the original one, but the one from the `CatchUnhandledException()` method of either the `WindowsServiceHost` or `ConsoleRunHost` class, that gets invoked because you the following line of your setup code:

```c#
x.UnhandledExceptionPolicy = Topshelf.Runtime.UnhandledExceptionPolicyCode.LogErrorAndStopService;
```

To trace this exception to its origin, first you might want to set `UnhandledExceptionPolicy` to `TakeNoAction`.

Then add something like the following lines to your code:

```c#
// Add this field to your Setup class.
private static int _firstChanceExceptionReentrancyLocked;

// Add this code to your startup/setup method.
AppDomain.CurrentDomain.FirstChanceException += (sender, eventArgs) =>
{
    if (Interlocked.CompareExchange(ref _firstChanceExceptionReentrancyLocked, 1, 0) == 0)
    {
        try
        {
            StackTrace currentStackTrace;

            try
            {
                currentStackTrace = new StackTrace(1, true);
            }
            catch
            {
                currentStackTrace = null;
            }
            
            logger.LogError(eventArgs.Exception, new StringBuilder()
                .AppendLine($"{DateTime.Now:O} {serviceName} exception thrown: {eventArgs.Exception.Message}")
                .AppendLine("----- Exception -----")
                .AppendLine(eventArgs.Exception.ToString().TrimEnd())
                .AppendLine("----- Full Stack -----")
                .AppendLine(currentStackTrace?.ToString().TrimEnd())
                .AppendLine()
                .ToString());
        }
        catch
        {
            // ignored
        }
        finally
        {
            Interlocked.Exchange(ref _firstChanceExceptionReentrancyLocked, 0);
        }
    }
}
```

This will log *every* exception, even those that get caught.

**Comment by phatboyg** [comment]
I am closing all issues that haven't seen any activity. You're welcome to submit a PR to resolve the issue or provide more information.
