### ISSUE TITLE
Cannot start as local windows service - InvalidOperationException / Win32Exception

### ISSUE THREAD

**Issue by JeReT** [Topshelf/Topshelf#594]
Hi,
I am trying to install and start my service. And it works as long as I install the executable where Visual Studio has build it.
However, when I copy it to a different folder, I get the following console output:

```
Service.exe install start
Configuration Result:
[Success] Name GamInfectionService
[Success] DisplayName Gam Infection Service
[Success] Description Runs sientific calculations with the goal of finding potential drugs for deseases like lung infection.
[Success] ServiceName GamInfectionService
Topshelf v4.3.0.0, .NET Framework 4.8.4250.0 (4.0.30319.42000)

Running a transacted installation.

Beginning the Install phase of the installation.
Installing Gam Infection Service service
Installing service GamInfectionService...
Service GamInfectionService has been successfully installed.

The Install phase completed successfully, and the Commit phase is beginning.

The Commit phase completed successfully.

The transacted install has completed.
Topshelf.Hosts.StartHost Error: 0 : The service failed to start., System.InvalidOperationException: Cannot start service GamInfectionService on computer '.'. ---> System.ComponentModel.Win32Exception: access is denied
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.StartService(String serviceName, TimeSpan startTimeOut)
   at Topshelf.Hosts.StartHost.Run()
```

I am new to development of Windows Services, so, I am not sure if it is caused because...

- ... I do some I/O stuff (`File.ReadAllLines("myFile.txt")`)
- ... I start another `Process` from within the service (Of course I copied that Programm over as well)

Any ideas?

**Comment by JeReT** [comment]
It turned out that I had to `RunAsLocalSystem()` rather than `RunAsLocalService`.
That created a similar error but with a different text (cannot find file). To solve this I had to put `Directory.SetCurrentDirectory(AppDomain.CurrentDomain.BaseDirectory);` as first instruction of the program.
Sorry for the false alarm (However, some hints in the documentation would be helpful).
