### ISSUE TITLE
Deploying to 2016 server targeting .net 5 PlatformNotSupportedException

### ISSUE THREAD

**Issue by richard-rodriquez** [Topshelf/Topshelf#598]
Thank you for taking your time to read this information.  I am trying to deploy my console application on a 2016 x64 bit server and I am getting the following error.  I am targeting .net 5. core.   Is .net 5 supported and can you point me in the right direction? Any thoughts would be appreciated.  Just looking for a second pair of eyes.  The .net 5 runtime is installed on the server and I am deploying this app self contained.  

2021-05-24 13:05:20.8057 Fatal  Monitor service was stopped because of exception System.InvalidOperationException: The installation failed, and the rollback has been performed.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ServiceProcess.ServiceProcessInstaller.GetLoginInfo()
   at System.ServiceProcess.ServiceInstaller.Install(IDictionary stateSaver)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at Topshelf.Runtime.Windows.HostInstaller.Install(IDictionary stateSaver)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
   --- End of inner exception stack trace ---
   at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
   at Topshelf.Runtime.Windows.HostServiceInstaller.InstallService(Action`1 beforeInstall, Action`1 afterInstall, Action`1 beforeRollback, Action`1 afterRollback)
   at Topshelf.Runtime.Windows.WindowsHostEnvironment.InstallService(InstallHostSettings settings, Action`1 beforeInstall, Action afterInstall, Action beforeRollback, Action afterRollback)
   at Topshelf.Hosts.InstallHost.Run()

It throwing this exception when initializing the HostFactory

**Comment by phatboyg** [comment]
Topshelf is no longer updated for newer runtimes. For NET5 just use the generic host.
