### ISSUE TITLE
TopShelf-based application does not start up

### ISSUE THREAD

**Issue by scampsd** [Topshelf/Topshelf#609]
This question is a copy from [this StackOverflow question](https://stackoverflow.com/questions/72558441).

I'm working on a DLL. The DLL was linked by a TopShelf-based application. Everything has worked before.
Now I get following error message (with full callstack):

```
Topshelf.HostFactory Error: 0 : An exception occurred creating the host, 
Topshelf.ServiceBuilderException: An exception occurred creating the service: 
MyApplicationServer ---> System.TypeInitializationException: 
The type initializer for 'Application.Server.ApplicationServer' threw an exception. 
---> System.UnauthorizedAccessException:
Access to the path 'Global\Application Server' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Application.Server.ApplicationServer..cctor()
   --- End of inner exception stack trace ---
   at Application.Server.ApplicationServer.get_Instance()
   at Application.Server.Program.<>c.<Main>b__2_2(HostSettings name)
   at Topshelf.Builders.DelegateServiceBuilder`1.Build(HostSettings settings)
   --- End of inner exception stack trace ---
   at Topshelf.Builders.DelegateServiceBuilder`1.Build(HostSettings settings)
   at Topshelf.Builders.RunBuilder.Build(ServiceBuilder serviceBuilder)
   at Topshelf.HostConfigurators.HostConfiguratorImpl.CreateHost()
   at Topshelf.HostFactory.New(Action`1 configureCallback)
Topshelf.HostFactory Error: 0 : The service terminated abnormally, Topshelf.ServiceBuilderException: An exception occurred creating the service: ApplicationServer ---> System.TypeInitializationException: The type initializer for 'Application.Server.ApplicationServer' threw an exception. ---> System.UnauthorizedAccessException: Access to the path 'Global\Application Server' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Application.Server.ApplicationServer..cctor()
   --- End of inner exception stack trace ---
   at Application.Server.ApplicationServer.get_Instance()
   at Application.Server.Program.<>c.<Main>b__2_2(HostSettings name)
   at Topshelf.Builders.DelegateServiceBuilder`1.Build(HostSettings settings)
   --- End of inner exception stack trace ---
   at Topshelf.Builders.DelegateServiceBuilder`1.Build(HostSettings settings)
   at Topshelf.Builders.RunBuilder.Build(ServiceBuilder serviceBuilder)
   at Topshelf.HostConfigurators.HostConfiguratorImpl.CreateHost()
   at Topshelf.HostFactory.New(Action`1 configureCallback)
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

```
As far as I know, nothing has been changed: my application was working fine. I have switched to another runtime directory and now I've switched back.

Until now, I have modified the permissions (the runtime directory was read-only) but this did not solve the issue.

What can I do?

I had seen that the directory (the runtime directory, which contains the application's *.exe file) is read-only, as you can see:

![image](https://user-images.githubusercontent.com/13345645/172836919-1652ea89-a542-4a1b-85d3-893c9b3db5e0.png)

I have tried unchecking that "Read-Only" checkbox, but it keeps on coming back, I don't know why.

**Comment by scampsd** [comment]
The issue was caused by the fact that the application was already running as a Windows Service.
